name = "podcastimages"
compatibility_date = "2022-11-19"
node_compat = true
routes = [
	{ pattern = "SUBDOMAIN.DOMAIN.COM", custom_domain = true, zone_name = "DOMAIN.COM" }
]

[vars]
API_KEY = "API_KEY"
API_SECRET = "API_SECRET"
CLOUDFLARE_ACCOUNT_ID = "CLOUDFLARE_ACCOUNT_ID"
CLOUDFLARE_ACCOUNT_HASH = "CLOUDFLARE_ACCOUNT_HASH"
CLOUDFLARE_API_TOKEN = "CLOUDFLARE_API_TOKEN"